### ISSUE TITLE
Search Order/Receipt History (7 APIs)

### ISSUE THREAD

**Issue by anle404** [RantoPhantom/swe30003-asm3-gr-4#4]
Search Order: Name, Date, Type (ONLINE/DINE IN), Status(PENDING, COMPLETED)

Search Receipt: Name, Date, Payment Method(Cash, Credit Card)

**Comment by anle404** [comment]
Return tạm thời làm giống get all nha (có gì thay đổi tính sau hihi)

**Comment by RantoPhantom** [comment]
no D:
